### ISSUE TITLE
copy keymaps folder to package when building

### ISSUE THREAD

**Issue by thewh1teagle** [thewh1teagle/zero-hid#3]
config package build setup to include keymaps folder

https://github.com/thewh1teagle/zero-hid/blob/main/MANIFEST.IN

```bash
$ python3
Python 3.9.7 (default, Aug 31 2021, 13:28:12)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zero_hid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/zero_hid/__init__.py", line 2, in <module>
    from .Keyboard import Keyboard
  File "/home/user/.local/lib/python3.9/site-packages/zero_hid/Keyboard.py", line 11, in <module>
    class Keyboard:
  File "/home/user/.local/lib/python3.9/site-packages/zero_hid/Keyboard.py", line 12, in Keyboard
    US_KEYBOARD = json.loads( pkgutil.get_data(__name__, "keymaps/US.json").decode() )
  File "/usr/lib/python3.9/pkgutil.py", line 639, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/lib/python3.9/site-packages/zero_hid/keymaps/US.json'
```

**Comment by thewh1teagle** [comment]
Fixed https://github.com/thewh1teagle/zero-hid/commit/23531049e3593e55cfde6bdd39120beb42de6442

**Comment by thewh1teagle** [comment]
When adding data files in non root folder of package, the folder MUST include __init__.py file
